### ISSUE TITLE
SoftDeleted records being returned when fetched from related models

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#105] opened 2015-07-14 17:37 UTC
Note, i'm using v.1.2.5

After soft deleting a record, the graph shows the `deleted_at` field with the expected timestamp set. However, the record is still returned. See code below:

```
use Vinelab\NeoEloquent\Eloquent\SoftDeletes;

class User extends NeoEloquent {

    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function cover()
    {
        return $this->hasOne('App\Graph\Photo', 'COVER_PHOTO');
    }

}
```

After performing a SoftDelete like so:.

```
$cover = $user->cover;
$cover->delete();
```

`$cover = $user->cover` still returns the record even though the `deleted_at` field `isset` and `NOT NULL`

Anyone else come across this?

Best,

**Comment by marlongichie** [comment] 2015-07-15 19:47
To update, I am also noticing the same behavior with hasMany relationships.

**Comment by marlongichie** [comment] 2015-07-19 07:03
@Mulkave Any chance you can take a look into this for me? Or maybe point me in the right direction

**Comment by tomb10516** [comment] 2015-07-21 19:57
Confirmed in 1.2.6.

I wrote a test that demonstrates this bug.  Please see testSoftDeletingModelWithRelated in https://github.com/tomb10516/NeoEloquent/blob/issue105/tests/functional/HasOneRelationTest.php

What should the behavior be?  Should the edge be marked as deleted as well, or should hasOne be checking deleted status?  I can probably fix this, but I want to be sure what the behavior should be before I make it behave that way :-)

**Comment by tomb10516** [comment] 2015-07-21 20:06
@Mulkave @marlongichie 

Update:  I want to also know if this is a bug.  I wrote the test using the same syntax as marlogichie.  When I use the syntax that I use in my projects I get the behavior I expect:

The syntax used in the test:

        $shouldBeNull = $user->profile;
        $this->assertNull($shouldBeNull);

The syntax I use in my own projects:

        $shouldBeNull = $user->profile->first();
        $this->assertNull($shouldBeNull);

I thought at first that the syntax in marlongichie's code was a mistake and that was what was causing the problem, but when I looked at testSavingRelatedHasOneModel I see the following syntax when accessing the related model:         // Let's retrieve it to make sure that NeoEloquent is not lying about it.
        $saved = User::find($user->id);
        $this->assertEquals($profile, $saved->profile);

To me this syntax is problematic because it seems to make the difference between properties and relations confusing.  My developers were using this latter syntax and I refactored to use my syntax and several bugs in our code went away.

**Comment by marlongichie** [comment] 2015-07-21 20:15
This use of this syntax is based on Eloquent's use of dynamic properties which automatically loads the relationship for you.

See here:
http://laravel.com/docs/5.0/eloquent#dynamic-properties

**Comment by tomb10516** [comment] 2015-07-21 20:25
@marlongichie 

Ok.  So let's do it that way, since Eloquent users will be used to that (I used Eloquent only briefly before switching to NeoEloquent, so I don't know all of standard Eloquent usage).

The behavior you are expecting then is that $user->profile  should be performing the HasOne method rather than looking at the current $user->profile object stored in memory?  Should the model be responding to some event that refreshed the $user object in memory to match the database?

**Comment by marlongichie** [comment] 2015-07-21 20:40
The expected behaviour is achieved by adding `whereNull` using the `deleted_at` field to the method that performs the `hasOne` relationship as shown below:

```
/**
     *
     * @return App\Graph\Profile
     */
    public function profile()
    {
        return $this->hasOne('App\Graph\Profile', 'HAS')->whereNull('profile.deleted_at');
    }
```

**Comment by tomb10516** [comment] 2015-07-21 21:01
I'm pretty sure it is compiling the queries correctly and the problem is that it is reading from the cache instead of running a fresh query.

I did a quick test and confirmed that the $shouldBeNull = $user->profile is not causing a query to be run.

I'll try to fix this.

**Comment by marlongichie** [comment] 2015-07-21 21:43
I'm doubting that's the case, the behaviour has been experience across multiple machines. As in, a record deleted by one user is not shown as deleted to another user on a different machine, so this wouldn't necessarily be from the cache would it?

**Comment by tomb10516** [comment] 2015-07-21 23:56
Well right now I don't see anywhere that the related models are getting touched on delete().  Are they supposed to be getting touched?  Right now there isn't anything in NeoEloquent which adds related models to Model::touches or similar.

**Comment by tomb10516** [comment] 2015-07-22 18:04
Ok,  This took me a surprisingly long time to figure out.

For the specific example you give, NeoEloquent's behavior matches Eloquent's.  (details below).  If you can give a more detailed example of what you think differs, or better yet a functional test, I'll take a deeper look, but so far I don't see the bug.

Here is the test I used using Eloquent models that correspond to the NeoEloquent models in the test I mentioned in https://github.com/tomb10516/NeoEloquent/blob/issue105/tests/functional/HasOneRelationTest.php

Note, both User and Profile extend lluminate\Database\Eloquent\Model and use Illuminate\Database\Eloquent\SoftDeletes

  public function testNETH()
    {
        $user = User::create(['name' => 'Tests', 'email' => 'B']);
        $profile = Profile::create(['guid' => uniqid(), 'service' => 'twitter']);

        $profile = $user->profile()->save($profile);
        $this->assertNotNull($user->profile);
        
        $profileLoaded = $user->profile;
        $profileLoaded->delete();
        
        $shouldBeNull = $user->profile;
        $this->assertNull($shouldBeNull);
    }

This test fails on the final assertion since $user->profile is not null.

**Comment by marlongichie** [comment] 2015-07-22 20:08
Correct me if I am wrong, but does this test suggest that the intended behaviour is for `$user->profile` to return both active as well as soft deleted records?

I still believe that this is a bug since the Eloquent documentation states that:

```
When querying a model that uses soft deletes, the "deleted" models will not be included in query results.
```
and then goes on to state:
```
To force soft deleted models to appear in a result set, use the withTrashed method on the query:

$user->posts()->withTrashed()->get();
```
http://laravel.com/docs/5.0/eloquent#soft-deleting

For now, I will continue using a workaround for my particular use case, but I think ill have to have a deeper look when I get a chance.

**Comment by tomb10516** [comment] 2015-07-22 20:16
@marlongichie 

I'd love it if you could let me know what you find when you have a chance for a deeper look!  Especially if you can show me code that works as you expect with Eloquent and not with NeoEloquent.

To answer your question though, I am not making any statement about what Eloquent should be doing in that case, only reporting what it does when tested.  To me it looks like a bug in Eloquent, but that is outside of my scope.  Perhaps you want to post the question on StackExchange or the Eloquent forums?

One thing to point out, is that while what they say in the documentation you quoted:
"When querying a model that uses soft deletes, the "deleted" models will not be included in query results."

Certainly suggests that $user->profile should be null after $profile has been deleted, they don't at least in that quote tell you that $user->profile is actually a fresh query rather than returning you a cached value from memory.  As I mentioned, both in Eloquent and NeoEloquent, $user->profile()->get() returns null after the profile has been soft deleted.

I'm not sure that Eloquent guarantees that cached dynamic properties will be updated on delete of a related model.

**Comment by tomb10516** [comment] 2015-08-24 17:37
@marlongichie 

I've made some improvements to handling of soft deletes, would you please try https://github.com/tomb10516/NeoEloquent/tree/1.2.6 and see if it fixes your problem?

**Comment by TheM1984** [comment] 2016-08-25 13:32
Am I correct to say that this bug is still open?

**Comment by uglymanfirst** [comment] 2018-07-24 14:15
Yes, I am trying to bring relationships of the **hasMany** type and it continues to bring in deleted data. I tried to insert a filter next to the relationship using **"whereNull('node.deleted_at')"** but apparently it has no effect on the selection.

Selecting the data directly was the only way to continue bringing this related data, so I'm thinking of implementing a call to bring only the id's and then continue making a direct selection on the entity by bringing the related data with **"whereIn('id', $array_ids)"**.

Provisionaly can solve the problem, but I do not think it is performative in my case.

hey @tomb10516, your fork solve the problem?
I am currently using the **"vinelab/neoeloquent"** version: **"^ 1.4"** in my composer, and **version 3.2.3 of Neo4j**. Is your version compatible?

Thanks in advance.

**Closed** 2020-07-27 15:26 UTC
Labels: Bug, Wontfix
