### ISSUE TITLE
QueryException when using orderBy

### ISSUE THREAD

**Issue by yavand** [Vinelab/NeoEloquent#253] opened 2017-11-22 12:56 UTC
Hi, in Laravel 5.5 when i use orderBy in my query i get Query Exception:

SyntaxException: Variable `advertise` not defined (line 1, column 56 (offset: 55)) "MATCH (advertise:`Advertise`) RETURN count(*) ORDER BY advertise.created_at DESC"

this because in query advertise not returned and if return advertise everything is ok:
"MATCH (advertise:`Advertise`) RETURN advertise, count(*) ORDER BY advertise.created_at DESC"

but i dont know how to correct this problem, please help me, thanks.

**Comment by KinaneD** [comment] 2017-11-22 13:19
Hi @yavand, what is the expected result of the query? If it's to count the advertisers there is no reason to order the result, since it's a integer.

**Comment by yavand** [comment] 2017-11-22 13:30
@KinaneD this is my query: 
return \App\Advertise::latest()->paginate(10);

if i remove paginate() or latest() the error is not occured.
in Laravel 5.3 there is no problem but in laravel 5.4 and 5.5 i have this problem :(

**Comment by yavand** [comment] 2017-11-23 07:06
I run this query: 
return \App\Advertise::latest()->paginate(10);

how can i correct this query and add advertise parameter into return?

MATCH (advertise:`Advertise`) RETURN count(*) ORDER BY advertise.created_at DESC

I want to add `advertise` in return statement before count(*): 

MATCH (advertise:`Advertise`) RETURN advertise, count(*) ORDER BY advertise.created_at DESC

please help me, this is very emergancy!

**Comment by magnajoaopolo** [comment] 2017-12-13 12:11
@yavand I believe the paginate() isn't ported to neoeloquent. You can try to implement the paginate() by your own using the limit clause.

**Comment by Mulkave** [comment] 2017-12-21 09:42
@yavand were you able to work it out? I'm not aware of the cause of this.

**Comment by yavand** [comment] 2017-12-21 11:28
@Mulkave in laravel v5.3 neoEloquent working without any problem in qurey that contain both of orderBy and paginate functions
for example:
Model::orderBy('name', 'DESC')->paginate(10);
but in laravel 5.4 and 5.5 neoEloquent returns Query exception if i use both of them in one query.
please help me. thanks

**Comment by yavand** [comment] 2017-12-22 10:57
@Mulkave when i execute this query:
$doctors = App\Doctor::latest()->paginate();
i got this error:

Vinelab\NeoEloquent\QueryException with message 'SyntaxException: Variable `doctor` not defined (line 1, column 50 (offset: 49))
"MATCH (doctor:`Doctor`) RETURN count(*) ORDER BY doctor.created_at DESC"

**Comment by Mulkave** [comment] 2018-01-30 13:03
Thanks for reporting. Appreciate a PR if you got the time.

**Comment by dgerike** [comment] 2018-06-14 13:34
Can't reproduce in Laravel 5.6. No exceptions and the result sets are looking good, too. 

I suppose this issue has been fixed in NeoEloquent 1.4.6.

**Closed** 2020-07-27 15:26 UTC
Labels: Bug, Compatibility, Wontfix
