### ISSUE TITLE
Error saving relationship.

### ISSUE THREAD

**Issue by tomb10516** [Vinelab/NeoEloquent#76] opened 2015-05-11 22:25 UTC
I think that this might be a bug in the library.  If so let me know and I might try to fix.  If not give me some idea of what is wrong with my code.  Thanks!

What is happening is that when I retrieve an edge then try to save it again I get an exception:

"ErrorException: substr() expects parameter 1 to be string, object given" (stack trace below)

A little digging shows me that what is happening is that 
vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Eloquent/Edges/Relation.php:316
which is the setRelation() method

is calling vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3116
which is the setConnection($name) method

and instead of passing a string for $name as Model::setConnection() expects it passes a Vinelab\NeoEloquent\Connection as $name

So is this an error in my code, or a bug in the library?  As far as I can tell Model::setConnection() should always be passed a string.

Here is the model I am using for testing:

class TestModel extends NeoEloquent {

    protected $connection = 'neo4j';
    public $label = 'LPN_TestModel';
  
    public function otherModel() {
        return $this->belongsTo('\App\Models\LPN\TestModel', 'LPN_TEST_RELATION');
    }

}

Here is the test code:

/**
 * @author tomb
 */
class TestModelTest extends \TestCase {

    public function testRelation() {
        $model1 = new \App\Models\LPN\TestModel();
        $model1->save();
        $model2 = new \App\Models\LPN\TestModel();
        $model2->save();
        $edge = $model1->otherModel()->associate($model2);
        $edge->save();
        
        $retreivedEdge = $model1->otherModel()->edge($model2);
        $retreivedEdge->save();
    }

}

And here is the Exception generated with stack trace

There was 1 error:

1) App\Models\LPN\TestModelTest::testRelation
ErrorException: substr() expects parameter 1 to be string, object given

/var/www/project/vendor/laravel/framework/src/Illuminate/Support/Str.php:87
/var/www/project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:92
/var/www/project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:61
/var/www/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3155
/var/www/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3116
/var/www/project/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Eloquent/Edges/Relation.php:316
/var/www/project/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Eloquent/Edges/Relation.php:221
/var/www/project/tests/TestModelTest.php:20
/usr/share/php/PHPUnit/TextUI/Command.php:176
/usr/share/php/PHPUnit/TextUI/Command.php:129

Versions from my composer.log:

            "name": "laravel/framework",
            "version": "v5.0.29",
            "name": "vinelab/neo4jphp",
            "version": "v0.1.1",
            "name": "vinelab/neoeloquent",
            "version": "v1.2.5",

If you have any thoughts I'd appreciate it!  If it looks to you like a bug in the library I am willing to invest some time in debugging it.

**Comment by Mulkave** [comment] 2015-05-11 22:48
@tomb10516 seems to be a bug, the connection name should never be passed as an object instead of a string. Would love to see a PR resolving it if you're interested.

**Comment by tomb10516** [comment] 2015-05-12 00:39
Ok, thanks!

I'll look into it more and see if I can come up with a patch.  Any advice you have on where to look is appreciated, but I'll start to look at it myself and report progress.  I partially posted the bug report to make sure it wasn't something you were already addressing in version 2.0 which I noticed there was a branch for.

**Comment by Mulkave** [comment] 2015-05-12 13:05
Actually it is being addressed yes, but there is no specific ETA for 2.0 (probably will be 1.5 instead) supposedly between end of week and mid next week. Otherwise you might want to look at the part that initializes a model and sets its connection, and since this has to do with the edge then you might want to look at `src/Vinelab/NeoEloquent/Eloquent/Edges|Relations` the best way to go about it is to reproduce it with a functional test (check `src/Vinelab/NeoEloquent/tests/functional/QueryingRelationsTest`)

**Comment by Sjaakmoes** [comment] 2015-06-01 10:31
Should be fixed with #85. setRelation used the getConnection() method from the related model instead of getConnectionName()

**Comment by Mulkave** [comment] 2015-06-01 10:32
Thanks @Sjaakmoes for the PR. Cheers 🍻

**Closed by Mulkave** 2015-06-01 10:32 UTC
Labels: Bug
