### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by adibhanna** [Vinelab/NeoEloquent#84] opened 2015-05-26 16:39 UTC
when trying this code: ``` dd(User::paginate(2));``` in my controller; i'm getting the following exception:
```ErrorException in CypherGrammar.php line 641: Undefined index: label``` 
I'm using NeoEloquent v1.2.5

**Comment by Mulkave** [comment] 2015-07-07 20:56
@adibhanna can you please try with v1.2.6?

**Comment by gauravdave01** [comment] 2015-08-03 09:28
Though updating to 1.2.6, still gives Undefined index: label error

**Comment by anujgandhi** [comment] 2015-08-04 13:42
Hello @Mulkave,

I am facing the same issue as @adibhannaI and am using Laravel 5.0.x for which v1.2.6 of NeoEloquent is not compatible.

I tried to hack my way by force setting the label as the values from ```$query->from``` in ```compileColumns(Builder $query, $properties)```:
```
if (count($query->from) == 1) {
    $query->aggregate['label'] = implode(',', $query->from);
}
```
At this point a 'percentile' key related error was thrown. To resolve this I set ```$aggregate['percentile']``` to ```null``` provided if the 'percentile' key did not exist in the ```$aggregate``` in ```compileAggregate(Builder $query, $aggregate)```:
```
if (!array_key_exists('percentile', $aggregate)) {
    $aggregate['percentile'] = null;
}
```
However, I got ```"ErrorException in vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php line 1440: Undefined index: aggregate"```

Looking forward to any suggestions/fixes

Thanks!

**Comment by tomb10516** [comment] 2015-08-04 13:44
@gauravdave01 

What version of Laravel are you using?  I may try to replicate your problem in a functional test, but I'd like confirmation that the problem exists in a supported configuration (Laravel 5.1.x with NeoEloquent v1.2.6)

**Comment by gauravdave01** [comment] 2015-08-05 06:24
I have used Laravel 5.1 and 1.2.6 of NeoEloquent.

**Comment by Mulkave** [comment] 2015-08-05 07:15
@anujgandhi can you please post the code that produced this issue? wondering about the use of `$aggregate['percentile'] = null` in the first place.

**Comment by anujgandhi** [comment] 2015-08-05 07:27
@Mulkave Below is part of my code:

Model:
```
class Currency extends PlatformBaseModel {}
class PlatformBaseModel extends \NeoEloquent {}
```

Repository:
```
public function __construct(Currency $model) {
    $this->model = $model;
}

public function listing() {
    $fields = ['*'];
    $limit = 25;
    $query = $this->model->newQuery();
    
   try {
        return $query->paginate($limit, $fields);
    } catch (Exception $e) {
        throw new DBException($e->getMessage(), $e->getCode(), $e->getPrevious());
    }
}
```

Let me know if you need anything else.

Thanks!

**Comment by tomb10516** [comment] 2015-08-13 21:18
I confirm this bug on V1.2.6 and Laravel 5.1

I'm working on fixing it.  If anyone else has been working on it please let me know so we don't do redundant work.

**Comment by tomb10516** [comment] 2015-08-14 18:27
Ok,

I have a fix that works in my own application, but NeoEloquent does not have tests for pagination (otherwise the bug would have been exposed earlier).  I will write a test if I have time.

In the mean time please try my patched version and see if it works for you.  After it gets tested I'll create a pull request.

https://github.com/tomb10516/NeoEloquent/tree/paginateFix

**Comment by tomb10516** [comment] 2015-08-14 18:36
@Mulkave 

Abed, would you please take a quick look at my patch to tell me whether my approach is right or if I am missing something? https://github.com/tomb10516/NeoEloquent/commit/b84889ef331b9c6a3457cdefa0984b598470b8ae

The bug was being caused by CypherGrammar:: compileAggregate() looking for the label for the columns in the $aggregate array, and there was no code to set that value.

So what I did is have it get the label instead from the from field of the $query object since this is more or less what Eloquent's sqlGrammar does.

That exposed a second bug which is that the function assumed that $aggregate['pecentile'] exists.  easy fix.

That exposed a third bug which is that the Eloquent\Query\Builder::getCountForPagination expects the result to come back in an array with an 'aggregate' key and is not compatible with ResultSet.  I fixed this by overloading getCountForPagination leaving the code the same as the parent except for getting the count value out of the result set.

Do you think getting the label out of $query->from is ok?  Will this cause weirdness in aggregates that aren't simple pagination counts?  I don't think our current functional tests cover this very well, and I don't have code in my own applications that cover almost any aggregate cases.

**Comment by Mulkave** [comment] 2015-08-17 16:19
@tomb10516 will take a look tonight!

**Comment by marlongichie** [comment] 2015-08-18 23:01
+1 

Laravel 5.0.x 
NeoEloquent v1.2.5

**Comment by tomb10516** [comment] 2015-08-24 17:45
@marlongichie @adibhanna 

An updated fix is at https://github.com/tomb10516/NeoEloquent/tree/1.2.6 

Please let me know if you have a chance to test this against your applications because I have a couple of bug fixes in that branch that are almost tested well enough for a pull request.

**Comment by marlongichie** [comment] 2015-08-24 18:14
@tomb10516 

I am currently using L5.0 which I believe is not compatible with NeoEloquent v1.2.6

So, does your fix also apply to v1.2.5?

**Comment by tomb10516** [comment] 2015-08-24 18:22
@marlongichie 

I just looked over the diffs and I don't see anything that looks incompatible, but I unfortunately don't have enough time to actually build a 1.2.5 package and test it.  Sorry!

**Comment by Mulkave** [comment] 2015-10-02 10:05
@marlongichie have you had the change to try with 1.2.8?

**Comment by luisalvarez** [comment] 2015-10-08 17:30
So this bug fix is not merged ?

**Comment by Mulkave** [comment] 2015-10-09 09:39
@luisalvarez should've been in 1.2.8, just released 1.2.9 so yes.

**Comment by luisalvarez** [comment] 2015-10-09 13:06
I'm usign it with 1.2.8 and laravel 5.1 and it not merge the same problem still i apply the fix and now works,

**Comment by luisalvarez** [comment] 2015-10-09 13:14
I'll replicate the fix to make you a pull request, also i goin to include this fix
Solve for #95: Migrations in v1.2.5 on Laravel 5.1 were broken due to an array_diff #99.

Bescause i need it too

**Comment by Mulkave** [comment] 2015-10-09 13:15
@luisalvarez sounds great! Thanks for your efforts. Please make sure you branch out of 1.2.9.

**Comment by luisalvarez** [comment] 2015-10-09 13:34
Ready i make a pull request

**Closed** 2015-10-17 09:45 UTC
Labels: Bug
