### ISSUE TITLE
Support for Laravel 5.4.*

### ISSUE THREAD

**Issue by elanvans** [Vinelab/NeoEloquent#231] opened 2017-04-11 07:39 UTC
I get this issue, please fix / help me to install
   
Problem 1
    - Conclusion: remove laravel/framework v5.4.18
    - Conclusion: don't install laravel/framework v5.4.18
    - vinelab/neoeloquent v1.4.0 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - vinelab/neoeloquent v1.4.1 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - vinelab/neoeloquent v1.4.2 requires illuminate/pagination 5.3.* -> satisfiable by illuminate/pagination[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/pagination v5.3.0|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.16|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.23|don't install laravel/framework v5.4.18
    - don't install illuminate/pagination v5.3.4|don't install laravel/framework v5.4.18
    - Installation request for laravel/framework (locked at v5.4.18, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.18].
    - Installation request for vinelab/neoeloquent 1.4.* -> satisfiable by vinelab/neoeloquent[v1.4.0, v1.4.1, v1.4.2].

**Comment by Frisbeetarian** [comment] 2017-05-03 12:39
Any update on this please?

**Comment by AzeemMichael** [comment] 2017-05-04 13:59
this is duplicate of #221

**Closed** 2017-12-21 10:05 UTC
